name: terminal_decorate
description: >
  Terminal colorization (colorful command line) and text style decoration.
version: 0.3.0
environment: {sdk: ^3.3.4}
repository: https://github.com/aprosail/terminal-decorate
topics:
  - cli
  - color
  - command-line-color
  - terminal-colorization
  - terminal-decoration

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
