name: terminal_decorate
description: >
  Terminal colorization (colorful command line) and text style decoration.
version: 0.0.0
repository: https://github.com/aprosail/terminal-decorate
topics:
  - cli
  - cli-color
  - color
  - command-line
  - command-line-color
  - font-decoration
  - terminal
  - terminal-colorization
  - terminal-decoration

environment: {sdk: ^3.3.4}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
