name: terminal_decorate
description: >
  Terminal colorization and text style decoration
  based on the escape code defined in ANSI X3.64, ECMA-48, or ISO 6429.
version: 1.0.0
repository: https://github.com/aprosail/terminal-decorate

environment: {sdk: ^3.3.4}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
